### 1. Tensor: 
Fancy word for multi dimensional array(like numpy arrays)

In [13]:
import torch

# 1D tensor -> shape = (3,). Just shows number of elements
t_1= torch.tensor([1.0, 2.0, 3.0])
print(t)

# 2d tensor - > shape = (3,2)
t_2= torch.tensor([[1.0, 1.5],[2.0, 1.4],[3.0, 1.6]])
print(t_2)
print(t_2.shape)



tensor([[1.0000, 1.5000],
        [2.0000, 1.4000],
        [3.0000, 1.6000]])
tensor([[1.0000, 1.5000],
        [2.0000, 1.4000],
        [3.0000, 1.6000]])
torch.Size([3, 2])


### 2. Unsqeeze(dim)

Add a dimension of size 1 at position you choose

In [17]:
t= torch.tensor([1.0,2.0,3.0])
print(t)
t_unsq = t.unsqueeze(0)
print(t_unsq)
print(t_unsq.shape)

tensor([1., 2., 3.])
tensor([[1., 2., 3.]])
torch.Size([1, 3])


In [20]:
t_unsq = t.unsqueeze(1)
print(t)
print(t.shape)
print(t_unsq)
print(t_unsq.shape)

tensor([1., 2., 3.])
torch.Size([3])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


### 3. Squeeze

Remove dimension of size 1. Does not work on shape (2,3)

In [26]:
t = torch.tensor([1.0, 2.0, 3.0])
print(t.shape)
t_sq = t.squeeze()
print(t_sq)
print(t_sq.shape)

torch.Size([3])
tensor([1., 2., 3.])
torch.Size([3])


## STEP 1: Imports + Device

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim


device ='mps' if torch.backends.mps.is_available() else 'cpu'

## STEP 2: Fake data

In [36]:
x = torch.linspace(0,10,100).unsqueeze(1).to(device)

y= 2*x+1 + torch.randn(x.size()).to(device)*0.5 

print(y)


tensor([[ 2.5182],
        [ 2.0107],
        [ 1.2149],
        [ 1.0136],
        [ 1.5833],
        [ 2.2809],
        [ 2.1865],
        [ 2.5739],
        [ 2.6438],
        [ 2.7088],
        [ 3.5842],
        [ 3.1924],
        [ 3.4499],
        [ 3.6137],
        [ 3.3067],
        [ 3.9198],
        [ 4.6308],
        [ 4.2309],
        [ 5.1374],
        [ 5.7726],
        [ 4.7959],
        [ 4.8146],
        [ 5.6505],
        [ 6.3311],
        [ 5.3602],
        [ 6.0432],
        [ 5.8671],
        [ 6.7816],
        [ 6.5179],
        [ 6.3874],
        [ 7.1585],
        [ 6.5137],
        [ 6.6137],
        [ 8.0821],
        [ 8.4032],
        [ 7.4443],
        [ 8.8161],
        [ 9.3193],
        [ 9.4355],
        [ 8.8951],
        [ 9.1477],
        [ 8.1202],
        [ 9.8996],
        [ 9.4462],
        [ 9.9629],
        [10.1744],
        [10.4530],
        [10.3045],
        [10.3969],
        [10.7357],
        [10.1376],
        [11.2116],
        [11.

## STEP 3: Model

In [32]:
class LinearModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)
  
model=LinearModel().to(device)


## STEP 4: Loss + Optimizer

In [34]:
loss_fn = nn.MSELoss()
optimizer=optim.SGD(model.parameters(), lr=0.01)

## STEP 5: Train

In [37]:
epochs= 1000
for epoch in range(epochs):
  optimizer.zero_grad() # clears all gradients from previous batch. Needed before backward()
  outputs = model(x)
  loss= loss_fn(outputs, y)
  loss.backward()
  optimizer.step()

  if epoch % 100==0:
    print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# torch.no_grad -> when not training, just testing
# Training = zero_grad() → forward → loss → backward → step
# Evaluation = no_grad() → forward → check results

Epoch 0, Loss: 249.3893
Epoch 100, Loss: 0.5235
Epoch 200, Loss: 0.3654
Epoch 300, Loss: 0.3069
Epoch 400, Loss: 0.2853
Epoch 500, Loss: 0.2774
Epoch 600, Loss: 0.2744
Epoch 700, Loss: 0.2733
Epoch 800, Loss: 0.2729
Epoch 900, Loss: 0.2728


## STEP 6: Check learned parameters

In [40]:
for name, param in model.named_parameters():
  print(f'{name}: {param.data}')

linear.weight: tensor([[2.0062]], device='mps:0')
linear.bias: tensor([1.0383], device='mps:0')
